//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamousFolks.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FamousFolksEntities : DbContext
    {
        public FamousFolksEntities()
            : base("name=FamousFolksEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Folk> Folks { get; set; }
        public virtual DbSet<FolksExpertise> FolksExpertises { get; set; }
        public virtual DbSet<Expertise> Expertises { get; set; }
    }
}
